accounts:
- broker: 开源证券
  holdings:
  - code: '002230'
    cost: 43.666
    name: 科大讯飞
    shares: 2600
  - code: 002298
    cost: 9.041
    name: 中电鑫龙
    shares: 6100
  - code: '002153'
    cost: 9.319
    name: 石基信息
    shares: 6000
  - code: '512660'
    cost: 1.564
    name: 军工ETF
    shares: 32000
  - code: '600011'
    cost: 7.185
    name: 华能国际
    shares: 2900
  name: wp-ky
- broker: 开源证券
  holdings:
  - code: '000063'
    cost: 43.404
    name: 中兴通讯
    shares: 5000
  - code: '002266'
    cost: 7.546
    name: 融发核电
    shares: 12600
  - code: '515230'
    cost: 0.812
    name: 软件ETF
    shares: 81000
  - code: '601138'
    cost: 95.324
    name: 工业富联
    shares: 800
  - code: '159869'
    cost: 1.116
    name: 游戏传媒ETF
    shares: 38200
  - code: '603236'
    cost: 53.473
    name: 移远通信
    shares: 100
  - code: '002312'
    cost: 10.042
    name: 川发龙蟒
    shares: 400
  - code: '600111'
    cost: 47.214
    name: 北方稀土
    shares: 100
  - code: '002902'
    cost: 26.789
    name: 铭普光磁
    shares: 100
  - code: '002085'
    cost: 11.409
    name: 万丰奥威
    shares: 100
  name: ymj-ky
- broker: 国泰海通证券
  holdings:
  - code: '002230'
    cost: 42.345
    name: 科大讯飞
    shares: 2000
  - code: '600645'
    cost: 20.615
    name: 中源协和
    shares: 2000
  - code: '601888'
    cost: 59.041
    name: 中国中免
    shares: 600
  - code: '000505'
    cost: 5.921
    name: 京粮控股
    shares: 4500
  - code: 002298
    cost: 8.31
    name: 中电鑫龙
    shares: 3000
  - code: '002241'
    cost: 23.254
    name: 歌尔股份
    shares: 2000
  - code: '600410'
    cost: 17.488
    name: 华胜天成
    shares: 1200
  name: wp-gtht
