accounts:
- broker: 开源证券
  holdings:
  - code: '002230'
    cost: 44.509
    name: 科大讯飞
    shares: 2000
  - code: 002298
    cost: 9.041
    name: 中电鑫龙
    shares: 6100
  - code: '002153'
    cost: 9.319
    name: 石基信息
    shares: 6000
  - code: '512660'
    cost: 1.564
    name: 军工ETF
    shares: 32000
  - code: '600011'
    cost: 7.185
    name: 华能国际
    shares: 2900
  name: wp-ky
- broker: 开源证券
  holdings:
  - code: '000063'
    cost: 43.541
    name: 中兴通讯
    shares: 5000
  - code: '002266'
    cost: 7.707
    name: 融发核电
    shares: 11600
  - code: '515230'
    cost: 0.831
    name: 软件ETF
    shares: 71000
  - code: '601138'
    cost: 99.981
    name: 工业富联
    shares: 700
  - code: '159869'
    cost: 1.116
    name: 游戏传媒ETF
    shares: 38200
  - code: '603236'
    cost: 53.738
    name: 移远通信
    shares: 100
  - code: '002312'
    cost: 10.042
    name: 川发龙蟒
    shares: 400
  name: ymj-ky
- broker: 国泰海通证券
  holdings:
  - code: '002230'
    cost: 42.819
    name: 科大讯飞
    shares: 1500
  - code: '600645'
    cost: 20.615
    name: 中源协和
    shares: 2000
  - code: '601888'
    cost: 59.041
    name: 中国中免
    shares: 600
  - code: '000505'
    cost: 5.921
    name: 京粮控股
    shares: 4500
  - code: 002298
    cost: 8.31
    name: 中电鑫龙
    shares: 3000
  - code: '002241'
    cost: 25.006
    name: 歌尔股份
    shares: 1000
  - code: '600410'
    cost: 17.488
    name: 华胜天成
    shares: 1200
  - code: '000034'
    cost: 28.002
    name: 神州数码
    shares: 200
  name: wp-gtht
